# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AnWebService' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AnWebService

  target 'AnWebServiceTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AnWebServiceUITests' do
    inherit! :search_paths
    # Pods for testing
  end
  pod 'Alamofire'
  pod 'AASquaresLoading', '~> 1.0'
end
